// Kaartmarkers: plekken die gasten kennen moeten
// Categorieen: home, eat, shop, sight, park, transport

const mapPlaces = [
  // ── Het landgoed zelf ─────────────────────────────────────────────────────
  {
    id: 'martenastate-home',
    category: 'home',
    icon: '🏕️',
    name_nl: 'Camping Martenastate',
    name_en: 'Camping Martenastate',
    desc_nl: 'Jouw verblijfplaats. Rustig kamperen achter de eeuwenoude beuken van het landgoed.',
    desc_en: 'Your home base. Peaceful camping behind the ancient beeches of the estate.',
    addr_nl: 'De Wier 7A, 9056 PM Koarnjum',
    addr_en: 'De Wier 7A, 9056 PM Koarnjum',
    coord: [53.2010, 5.7738],
    externalUrl: 'https://maps.google.com/?q=De+Wier+7A,+9056+PM+Koarnjum',
    highlight: true,
  },
  {
    id: 'tunmanswente',
    category: 'eat',
    icon: '☕',
    name_nl: 'Túnmanswente',
    name_en: 'Túnmanswente',
    desc_nl: 'Sfeervolle theetuin op het landgoed. Koffie, thee en lunch. Open vr 13–17u, za/zo 11–17u (27 mrt – 25 okt).',
    desc_en: 'Atmospheric tea garden on the estate. Coffee, tea and lunch. Fri 13–17h, Sat/Sun 11–17h (27 Mar – 25 Oct).',
    addr_nl: 'Martenawei 2, Koarnjum',
    addr_en: 'Martenawei 2, Koarnjum',
    coord: [53.2015, 5.7748],
    externalUrl: 'https://www.tunmanswente.nl',
    badge_nl: 'Op het landgoed',
    badge_en: 'On the estate',
  },
  {
    id: 'martenastate-kasteel',
    category: 'sight',
    icon: '🏰',
    name_nl: 'Kasteel Martenastate',
    name_en: 'Martenastate Castle',
    desc_nl: 'Neo-renaissance kasteel uit 1899 met karakteristieke uienvormige toren. Nationaal monument — exterieur vrij te bezichtigen.',
    desc_en: 'Neo-renaissance castle from 1899 with characteristic onion-shaped tower. National monument — exterior freely accessible.',
    addr_nl: 'Martenawei 2, Koarnjum',
    addr_en: 'Martenawei 2, Koarnjum',
    coord: [53.2020, 5.7760],
    externalUrl: 'https://martenastate.nl',
  },
  {
    id: 'parking-landgoed',
    category: 'transport',
    icon: '🅿️',
    name_nl: 'Parkeerplaats landgoed',
    name_en: 'Estate car park',
    desc_nl: 'Gratis parkeerplaats bij de hoofdingang van het landgoed. Loopafstand naar Túnmanswente en het park.',
    desc_en: 'Free car park at the main estate entrance. Walking distance to Túnmanswente and the park.',
    addr_nl: 'Martenawei, Koarnjum',
    addr_en: 'Martenawei, Koarnjum',
    coord: [53.2012, 5.7742],
    externalUrl: 'https://maps.google.com/?q=53.2012,5.7742',
  },

  // ── Winkels & dagelijkse boodschappen ─────────────────────────────────────
  {
    id: 'ah-stiens',
    category: 'shop',
    icon: '🛒',
    name_nl: 'Albert Heijn Stiens',
    name_en: 'Albert Heijn Stiens',
    desc_nl: 'Grootste supermarkt in de buurt. Ma–za 8–21u, zo 10–19u.',
    desc_en: 'Largest nearby supermarket. Mon–Sat 8–21h, Sun 10–19h.',
    addr_nl: 'Geert Knolweg 1, 9051 ES Stiens',
    addr_en: 'Geert Knolweg 1, 9051 ES Stiens',
    coord: [53.2572, 5.7620],
    externalUrl: 'https://maps.google.com/?q=Albert+Heijn+Stiens',
    badge_nl: '4 km',
    badge_en: '4 km',
  },
  {
    id: 'bakker-stiens',
    category: 'eat',
    icon: '🥐',
    name_nl: 'Bakkerij Stiens',
    name_en: 'Bakery Stiens',
    desc_nl: 'Ambachtelijke bakkerij in het centrum van Stiens. Verse broden en Friese spezialiteiten. Gesloten ma.',
    desc_en: 'Artisan bakery in the centre of Stiens. Fresh bread and Frisian specialities. Closed Mon.',
    addr_nl: 'Centrum Stiens',
    addr_en: 'Stiens town centre',
    coord: [53.2578, 5.7640],
    externalUrl: 'https://maps.google.com/?q=Bakkerij+Stiens',
    badge_nl: '4 km',
    badge_en: '4 km',
  },

  // ── Restaurants Leeuwarden ─────────────────────────────────────────────────
  {
    id: 'resto-grietenij',
    category: 'eat',
    icon: '🍽️',
    name_nl: "De Grietenij",
    name_en: "De Grietenij",
    desc_nl: 'Sfeervolle eetcafé in het centrum. Goede bieren, hartelijk gerechten en een prettige sfeer. Reserveer op vrijdagavond.',
    desc_en: 'Atmospheric brasserie in the centre. Good beers, hearty dishes and a pleasant atmosphere. Book ahead on Friday evening.',
    addr_nl: 'Leeuwarden centrum',
    addr_en: 'Leeuwarden city centre',
    coord: [53.2010, 5.7995],
    externalUrl: 'https://maps.google.com/?q=De+Grietenij+Leeuwarden',
    badge_nl: '€€',
    badge_en: '€€',
  },
  {
    id: 'resto-wouters',
    category: 'eat',
    icon: '🍕',
    name_nl: "Wouters",
    name_en: "Wouters",
    desc_nl: 'Populair restaurant in het centrum van Leeuwarden. Goed voor lunch én dinner. Terras aan de gracht in de zomer.',
    desc_en: 'Popular restaurant in Leeuwarden city centre. Great for lunch and dinner. Canal-side terrace in summer.',
    addr_nl: 'Leeuwarden centrum',
    addr_en: 'Leeuwarden city centre',
    coord: [53.2025, 5.7980],
    externalUrl: 'https://maps.google.com/?q=Wouters+Leeuwarden',
    badge_nl: '€€',
    badge_en: '€€',
  },
  {
    id: 'oldehove-markt',
    category: 'eat',
    icon: '☕',
    name_nl: 'Waag (bij de Oldehove)',
    name_en: 'Waag (near the Oldehove)',
    desc_nl: 'Koffie en lunch met uitzicht op de scheve Oldehove-toren. Geweldig terras op mooie dagen.',
    desc_en: 'Coffee and lunch with a view of the leaning Oldehove tower. Wonderful terrace on sunny days.',
    addr_nl: 'Oldehoofsterkerkhof, Leeuwarden',
    addr_en: 'Oldehoofsterkerkhof, Leeuwarden',
    coord: [53.2031, 5.7931],
    externalUrl: 'https://maps.google.com/?q=Waag+Leeuwarden',
    badge_nl: '€',
    badge_en: '€',
  },

  // ── Bezienswaardigheden ─────────────────────────────────────────────────────
  {
    id: 'fries-museum',
    category: 'sight',
    icon: '🏛️',
    name_nl: 'Fries Museum',
    name_en: 'Fries Museum',
    desc_nl: 'Topmuseum met het verhaal van Friesland. Mata Hari-tentoonstelling, archeologie, kunst. Di–zo 11–17u.',
    desc_en: 'Top museum telling the story of Friesland. Mata Hari exhibition, archaeology, art. Tue–Sun 11–17h.',
    addr_nl: 'Wilhelminaplein 92, Leeuwarden',
    addr_en: 'Wilhelminaplein 92, Leeuwarden',
    coord: [53.2009, 5.7986],
    externalUrl: 'https://www.friesmuseum.nl',
    badge_nl: '5 km',
    badge_en: '5 km',
  },
  {
    id: 'oldehove',
    category: 'sight',
    icon: '🗼',
    name_nl: 'Oldehove',
    name_en: 'Oldehove',
    desc_nl: "Leeuwarden's scheve toren — scheef omdat hij te snel werd gebouwd (1529). Op te klimmen voor panorama. Zomerseizoenen open.",
    desc_en: "Leeuwarden's leaning tower — tilted because it was built too fast (1529). Climbable for panoramic views. Open in summer seasons.",
    addr_nl: 'Oldehoofsterkerkhof, Leeuwarden',
    addr_en: 'Oldehoofsterkerkhof, Leeuwarden',
    coord: [53.2029, 5.7929],
    externalUrl: 'https://maps.google.com/?q=Oldehove+Leeuwarden',
    badge_nl: '5 km',
    badge_en: '5 km',
  },
  {
    id: 'princessehof',
    category: 'sight',
    icon: '🏺',
    name_nl: 'Museum Princessehof',
    name_en: 'Museum Princessehof',
    desc_nl: 'Nationaal keramiekmuseum in het geboortehuis van Mata Hari. Wereldcollectie keramiek, aardewerk en porselein.',
    desc_en: 'National ceramics museum in the birthplace of Mata Hari. World collection of ceramics, pottery and porcelain.',
    addr_nl: 'Grote Kerkstraat 11, Leeuwarden',
    addr_en: 'Grote Kerkstraat 11, Leeuwarden',
    coord: [53.2020, 5.7970],
    externalUrl: 'https://www.princessehof.nl',
    badge_nl: '5 km',
    badge_en: '5 km',
  },
  {
    id: 'jelsum',
    category: 'sight',
    icon: '🌾',
    name_nl: 'Jelsum (dorpje)',
    name_en: 'Jelsum (village)',
    desc_nl: 'Pittoresk Fries weidedorp met een historische kerk. Vanuit Martenastate te bereiken via de Middagtocht (5 km).',
    desc_en: 'Picturesque Frisian village with a historic church. Reachable from Martenastate via the Afternoon walk (5 km).',
    addr_nl: 'Jelsum, Friesland',
    addr_en: 'Jelsum, Friesland',
    coord: [53.2214, 5.7694],
    externalUrl: 'https://maps.google.com/?q=Jelsum+Friesland',
    badge_nl: '5 km wandelen',
    badge_en: '5 km walk',
  },

  // ── Daguitjes ─────────────────────────────────────────────────────────────
  {
    id: 'harlingen',
    category: 'sight',
    icon: '⚓',
    name_nl: 'Harlingen',
    name_en: 'Harlingen',
    desc_nl: 'Authentieke Friese havenstad. Schepen, grachten, rustieke sfeer. Vertrek naar Waddeneilanden. 30 km rijden.',
    desc_en: 'Authentic Frisian harbour town. Ships, canals, rustic atmosphere. Ferries to the Wadden Islands. 30 km drive.',
    addr_nl: 'Harlingen, Friesland',
    addr_en: 'Harlingen, Friesland',
    coord: [53.1743, 5.4214],
    externalUrl: 'https://maps.google.com/?q=Harlingen+Friesland',
    badge_nl: '30 km',
    badge_en: '30 km',
  },
  {
    id: 'woudagemaal',
    category: 'sight',
    icon: '⚙️',
    name_nl: 'Woudagemaal (UNESCO)',
    name_en: 'Woudagemaal (UNESCO)',
    desc_nl: "Grootste nog in bedrijf zijnde stoomsgemaal ter wereld. UNESCO-werelderfgoed. Buiten seizoen ook bezienswaardig.",
    desc_en: "World's largest still-operating steam-powered pumping station. UNESCO World Heritage. Worth seeing even out of season.",
    addr_nl: 'Lemmer, Friesland',
    addr_en: 'Lemmer, Friesland',
    coord: [52.8484, 5.7103],
    externalUrl: 'https://www.woudagemaal.nl',
    badge_nl: '50 km',
    badge_en: '50 km',
  },
];
