// Kaartmarkers: plekken die gasten kennen moeten
// Categorieen: home, eat, shop, sight, park, transport

const mapPlaces = [
  // ── Het landgoed zelf ─────────────────────────────────────────────────────
  {
    id: 'martenastate-home',
    category: 'home',
    icon: 'tent',
    name_nl: 'Camping Martenastate',
    name_en: 'Camping Martenastate',
    name_de: "Camping Martenastate",
    desc_nl: 'Jouw verblijfplaats. Rustig kamperen achter de eeuwenoude beuken van het landgoed.',
    desc_en: 'Your home base. Peaceful camping behind the ancient beeches of the estate.',
    desc_de: "Dein Aufenthaltsort. Ruhiges Camping hinter den jahrhundertealten Buchen des Landguts.",
    addr_nl: 'De Wier 7A, 9056 PM Koarnjum',
    addr_en: 'De Wier 7A, 9056 PM Koarnjum',
    addr_de: "De Wier 7A, 9056 PM Koarnjum",
    coord: [53.2010, 5.7738],
    externalUrl: 'https://maps.google.com/?q=De+Wier+7A,+9056+PM+Koarnjum',
    highlight: true,
  },
  {
    id: 'tunmanswente',
    category: 'eat',
    icon: 'cup',
    name_nl: 'Túnmanswente',
    name_en: 'Túnmanswente',
    name_de: "Túnmanswente",
    desc_nl: 'Sfeervolle theetuin op het landgoed. Koffie, thee en lunch. Open vr 13–17u, za/zo 11–17u (27 mrt – 25 okt).',
    desc_en: 'Atmospheric tea garden on the estate. Coffee, tea and lunch. Fri 13–17h, Sat/Sun 11–17h (27 Mar – 25 Oct).',
    desc_de: "Stimmungsvoller Teegarten auf dem Landgut. Kaffee, Tee und Mittag. Fr 13–17 Uhr, Sa/So 11–17 Uhr (27. März – 25. Okt.).",
    addr_nl: 'Martenawei 2, Koarnjum',
    addr_en: 'Martenawei 2, Koarnjum',
    addr_de: "Martenawei 2, Koarnjum",
    coord: [53.2015, 5.7748],
    externalUrl: 'https://www.tunmanswente.nl',
    badge_nl: 'Op het landgoed',
    badge_en: 'On the estate',
    badge_de: "Auf dem Landgut",
  },
  {
    id: 'martenastate-kasteel',
    category: 'sight',
    icon: 'castle',
    name_nl: 'Kasteel Martenastate',
    name_en: 'Martenastate Castle',
    name_de: "Schloss Martenastate",
    desc_nl: 'Neo-renaissance kasteel uit 1899 met karakteristieke uienvormige toren. Nationaal monument — exterieur vrij te bezichtigen.',
    desc_en: 'Neo-renaissance castle from 1899 with characteristic onion-shaped tower. National monument — exterior freely accessible.',
    desc_de: "Neorenaissance-Schloss von 1899 mit markantem zwiebelförmigem Turm. Nationales Denkmal — Außenansicht frei zugänglich.",
    addr_nl: 'Martenawei 2, Koarnjum',
    addr_en: 'Martenawei 2, Koarnjum',
    addr_de: "Martenawei 2, Koarnjum",
    coord: [53.2020, 5.7760],
    externalUrl: 'https://martenastate.nl',
  },
  {
    id: 'parking-landgoed',
    category: 'transport',
    icon: '🅿️',
    name_nl: 'Parkeerplaats landgoed',
    name_en: 'Estate car park',
    name_de: "Parkplatz Landgut",
    desc_nl: 'Gratis parkeerplaats bij de hoofdingang van het landgoed. Loopafstand naar Túnmanswente en het park.',
    desc_en: 'Free car park at the main estate entrance. Walking distance to Túnmanswente and the park.',
    desc_de: "Kostenloser Parkplatz am Haupteingang des Landguts. Zu Fuß zur Túnmanswente und in den Park.",
    addr_nl: 'Martenawei, Koarnjum',
    addr_en: 'Martenawei, Koarnjum',
    addr_de: "Martenawei, Koarnjum",
    coord: [53.2012, 5.7742],
    externalUrl: 'https://maps.google.com/?q=53.2012,5.7742',
  },

  // ── Winkels & dagelijkse boodschappen ─────────────────────────────────────
  {
    id: 'ah-stiens',
    category: 'shop',
    icon: 'cart',
    name_nl: 'Albert Heijn Stiens',
    name_en: 'Albert Heijn Stiens',
    name_de: "Albert Heijn Stiens",
    desc_nl: 'Grootste supermarkt in de buurt. Ma–za 8–21u, zo 10–19u.',
    desc_en: 'Largest nearby supermarket. Mon–Sat 8–21h, Sun 10–19h.',
    desc_de: "Größter Supermarkt in der Nähe. Mo–Sa 8–21 Uhr, So 10–19 Uhr.",
    addr_nl: 'Geert Knolweg 1, 9051 ES Stiens',
    addr_en: 'Geert Knolweg 1, 9051 ES Stiens',
    addr_de: "Geert Knolweg 1, 9051 ES Stiens",
    coord: [53.2572, 5.7620],
    externalUrl: 'https://maps.google.com/?q=Albert+Heijn+Stiens',
    badge_nl: '4 km',
    badge_en: '4 km',
    badge_de: "4 km",
  },
  {
    id: 'bakker-stiens',
    category: 'eat',
    icon: 'croissant',
    name_nl: 'Bakkerij Stiens',
    name_en: 'Bakery Stiens',
    name_de: "Bäckerei Stiens",
    desc_nl: 'Ambachtelijke bakkerij in het centrum van Stiens. Verse broden en Friese spezialiteiten. Gesloten ma.',
    desc_en: 'Artisan bakery in the centre of Stiens. Fresh bread and Frisian specialities. Closed Mon.',
    desc_de: "Handwerksbäckerei im Zentrum von Stiens. Frisches Brot und friesische Spezialitäten. Mo geschlossen.",
    addr_nl: 'Centrum Stiens',
    addr_en: 'Stiens town centre',
    addr_de: "Zentrum Stiens",
    coord: [53.2578, 5.7640],
    externalUrl: 'https://maps.google.com/?q=Bakkerij+Stiens',
    badge_nl: '4 km',
    badge_en: '4 km',
    badge_de: "4 km",
  },

  // ── Restaurants Leeuwarden ─────────────────────────────────────────────────
  {
    id: 'resto-grietenij',
    category: 'eat',
    icon: 'fork_knife',
    name_nl: "De Grietenij",
    name_en: "De Grietenij",
    name_de: "De Grietenij",
    desc_nl: 'Sfeervolle eetcafé in het centrum. Goede bieren, hartelijk gerechten en een prettige sfeer. Reserveer op vrijdagavond.',
    desc_en: 'Atmospheric brasserie in the centre. Good beers, hearty dishes and a pleasant atmosphere. Book ahead on Friday evening.',
    desc_de: "Stimmungsvolles Eetcafé im Zentrum. Gute Biere, herzhafte Gerichte und angenehme Atmosphäre. Freitagabend reservieren.",
    addr_nl: 'Leeuwarden centrum',
    addr_en: 'Leeuwarden city centre',
    addr_de: "Leeuwarden Zentrum",
    coord: [53.2010, 5.7995],
    externalUrl: 'https://maps.google.com/?q=De+Grietenij+Leeuwarden',
    badge_nl: '€€',
    badge_en: '€€',
    badge_de: "€€",
  },
  {
    id: 'resto-wouters',
    category: 'eat',
    icon: 'pizza',
    name_nl: "Wouters",
    name_en: "Wouters",
    name_de: "Wouters",
    desc_nl: 'Populair restaurant in het centrum van Leeuwarden. Goed voor lunch én dinner. Terras aan de gracht in de zomer.',
    desc_en: 'Popular restaurant in Leeuwarden city centre. Great for lunch and dinner. Canal-side terrace in summer.',
    desc_de: "Beliebtes Restaurant im Zentrum von Leeuwarden. Gut für Mittag und Abendessen. Im Sommer Terrasse an der Gracht.",
    addr_nl: 'Leeuwarden centrum',
    addr_en: 'Leeuwarden city centre',
    addr_de: "Leeuwarden Zentrum",
    coord: [53.2025, 5.7980],
    externalUrl: 'https://maps.google.com/?q=Wouters+Leeuwarden',
    badge_nl: '€€',
    badge_en: '€€',
    badge_de: "€€",
  },
  {
    id: 'oldehove-markt',
    category: 'eat',
    icon: 'cup',
    name_nl: 'Waag (bij de Oldehove)',
    name_en: 'Waag (near the Oldehove)',
    name_de: "Waag (am Oldehove)",
    desc_nl: 'Koffie en lunch met uitzicht op de scheve Oldehove-toren. Geweldig terras op mooie dagen.',
    desc_en: 'Coffee and lunch with a view of the leaning Oldehove tower. Wonderful terrace on sunny days.',
    desc_de: "Kaffee und Mittag mit Blick auf den schiefen Oldehove-Turm. Tolle Terrasse an schönen Tagen.",
    addr_nl: 'Oldehoofsterkerkhof, Leeuwarden',
    addr_en: 'Oldehoofsterkerkhof, Leeuwarden',
    addr_de: "Oldehoofsterkerkhof, Leeuwarden",
    coord: [53.2031, 5.7931],
    externalUrl: 'https://maps.google.com/?q=Waag+Leeuwarden',
    badge_nl: '€',
    badge_en: '€',
    badge_de: "€",
  },

  // ── Bezienswaardigheden ─────────────────────────────────────────────────────
  {
    id: 'fries-museum',
    category: 'sight',
    icon: 'column',
    name_nl: 'Fries Museum',
    name_en: 'Fries Museum',
    name_de: "Fries Museum",
    desc_nl: 'Topmuseum met het verhaal van Friesland. Mata Hari-tentoonstelling, archeologie, kunst. Di–zo 11–17u.',
    desc_en: 'Top museum telling the story of Friesland. Mata Hari exhibition, archaeology, art. Tue–Sun 11–17h.',
    desc_de: "Top-Museum mit der Geschichte Frieslands. Mata-Hari-Ausstellung, Archäologie, Kunst. Di–So 11–17 Uhr.",
    addr_nl: 'Wilhelminaplein 92, Leeuwarden',
    addr_en: 'Wilhelminaplein 92, Leeuwarden',
    addr_de: "Wilhelminaplein 92, Leeuwarden",
    coord: [53.2009, 5.7986],
    externalUrl: 'https://www.friesmuseum.nl',
    badge_nl: '5 km',
    badge_en: '5 km',
    badge_de: "5 km",
  },
  {
    id: 'oldehove',
    category: 'sight',
    icon: 'tower',
    name_nl: 'Oldehove',
    name_en: 'Oldehove',
    name_de: "Oldehove",
    desc_nl: "Leeuwarden's scheve toren — scheef omdat hij te snel werd gebouwd (1529). Op te klimmen voor panorama. Zomerseizoenen open.",
    desc_en: "Leeuwarden's leaning tower — tilted because it was built too fast (1529). Climbable for panoramic views. Open in summer seasons.",
    desc_de: "Der schiefe Turm von Leeuwarden — schief, weil zu schnell gebaut (1529). Besteigen für Panoramablick. In der Sommersaison geöffnet.",
    addr_nl: 'Oldehoofsterkerkhof, Leeuwarden',
    addr_en: 'Oldehoofsterkerkhof, Leeuwarden',
    addr_de: "Oldehoofsterkerkhof, Leeuwarden",
    coord: [53.2029, 5.7929],
    externalUrl: 'https://maps.google.com/?q=Oldehove+Leeuwarden',
    badge_nl: '5 km',
    badge_en: '5 km',
    badge_de: "5 km",
  },
  {
    id: 'princessehof',
    category: 'sight',
    icon: 'vase',
    name_nl: 'Museum Princessehof',
    name_en: 'Museum Princessehof',
    name_de: "Museum Princessehof",
    desc_nl: 'Nationaal keramiekmuseum in het geboortehuis van Mata Hari. Wereldcollectie keramiek, aardewerk en porselein.',
    desc_en: 'National ceramics museum in the birthplace of Mata Hari. World collection of ceramics, pottery and porcelain.',
    desc_de: "Nationales Keramikmuseum im Geburtshaus von Mata Hari. Weltsammlung von Keramik, Steingut und Porzellan.",
    addr_nl: 'Grote Kerkstraat 11, Leeuwarden',
    addr_en: 'Grote Kerkstraat 11, Leeuwarden',
    addr_de: "Grote Kerkstraat 11, Leeuwarden",
    coord: [53.2020, 5.7970],
    externalUrl: 'https://www.princessehof.nl',
    badge_nl: '5 km',
    badge_en: '5 km',
    badge_de: "5 km",
  },
  {
    id: 'jelsum',
    category: 'sight',
    icon: 'wheat',
    name_nl: 'Jelsum (dorpje)',
    name_en: 'Jelsum (village)',
    name_de: "Jelsum (Dorf)",
    desc_nl: 'Pittoresk Fries weidedorp met een historische kerk. Vanuit Martenastate te bereiken via de Middagtocht (5 km).',
    desc_en: 'Picturesque Frisian village with a historic church. Reachable from Martenastate via the Afternoon walk (5 km).',
    desc_de: "Malerisches friesisches Wiesendorf mit historischer Kirche. Von Martenastate erreichbar über den Mittagsspaziergang (5 km).",
    addr_nl: 'Jelsum, Friesland',
    addr_en: 'Jelsum, Friesland',
    addr_de: "Jelsum, Friesland",
    coord: [53.2214, 5.7694],
    externalUrl: 'https://maps.google.com/?q=Jelsum+Friesland',
    badge_nl: '5 km wandelen',
    badge_en: '5 km walk',
    badge_de: "5 km zu Fuß",
  },

  // ── Daguitjes ─────────────────────────────────────────────────────────────
  {
    id: 'harlingen',
    category: 'sight',
    icon: 'anchor',
    name_nl: 'Harlingen',
    name_en: 'Harlingen',
    name_de: "Harlingen",
    desc_nl: 'Friese havenstad met oude gevels. Schepen, grachten. Vertrek naar de Waddeneilanden. 30 km rijden.',
    desc_en: 'Frisian harbour town with old gables. Ships, canals. Ferries to the Wadden Islands. 30 km drive.',
    desc_de: "Friesische Hafenstadt mit alten Giebeln. Schiffe, Grachten. Fähren zu den Watteninseln. 30 km Fahrt.",
    addr_nl: 'Harlingen, Friesland',
    addr_en: 'Harlingen, Friesland',
    addr_de: "Harlingen, Friesland",
    coord: [53.1743, 5.4214],
    externalUrl: 'https://maps.google.com/?q=Harlingen+Friesland',
    badge_nl: '30 km',
    badge_en: '30 km',
    badge_de: "30 km",
  },
  {
    id: 'woudagemaal',
    category: 'sight',
    icon: 'gear',
    name_nl: 'Woudagemaal (UNESCO)',
    name_en: 'Woudagemaal (UNESCO)',
    name_de: "Woudagemaal (UNESCO)",
    desc_nl: "Grootste nog in bedrijf zijnde stoomsgemaal ter wereld. UNESCO-werelderfgoed. Buiten seizoen ook bezienswaardig.",
    desc_en: "World's largest still-operating steam-powered pumping station. UNESCO World Heritage. Worth seeing even out of season.",
    desc_de: "Größtes noch in Betrieb befindliches Dampfpumpwerk der Welt. UNESCO-Welterbe. Auch außerhalb der Saison sehenswert.",
    addr_nl: 'Lemmer, Friesland',
    addr_en: 'Lemmer, Friesland',
    addr_de: "Lemmer, Friesland",
    coord: [52.8484, 5.7103],
    externalUrl: 'https://www.woudagemaal.nl',
    badge_nl: '50 km',
    badge_en: '50 km',
    badge_de: "50 km",
  },
];
