// Wandel- en fietsroutes vanaf Martenastate
//
// Alle externe links verwijzen naar officiële routebeschrijvingspagina's:
// - wandelnet.nl voor wandelroutes
// - friesland.nl voor fietsroutes
//
// Polylines zijn visuele indicaties; voor de echte routebeschrijving
// gebruik je de externe link.

const MARTENASTATE        = [53.2013, 5.7745];
const LEEUWARDEN_OLDEHOVE = [53.2031, 5.7929];
const BURGUM              = [53.1900, 6.0000];

const walkingRoutes = [
  {
    id: 'ochtendrondje',
    name_nl: 'Ochtendrondje door het park',
    name_en: 'Morning park loop',
    name_de: 'Morgenrunde durch den Park',
    distance: '~1,5 km',
    duration_nl: '±25 min',
    duration_en: '±25 min',
    duration_de: '±25 Min.',
    difficulty_nl: 'Gemakkelijk',
    difficulty_en: 'Easy',
    difficulty_de: 'Leicht',
    desc_nl: 'Wandel vrij door het landschapspark van Martenastate. Volg de hoofdpaden vanaf de ingang naar het kasteel en terug langs de stinzenflora-velden. Vlak terrein, paden zijn doorgaans goed begaanbaar.',
    desc_en: 'Wander freely through the Martenastate landscape park. Follow the main paths from the entrance to the castle and back past the stinzenflora fields. Flat terrain, paths are generally easy to walk.',
    desc_de: 'Spazieren Sie frei durch den Landschaftspark von Martenastate. Folgen Sie den Hauptwegen vom Eingang zum Schloss und zurück vorbei an den Stinzenflora-Feldern. Flaches Gelände, Wege sind in der Regel gut begehbar.',
    coords: [
      [53.2013, 5.7745],
      [53.2018, 5.7762],
      [53.2025, 5.7770],
      [53.2030, 5.7755],
      [53.2025, 5.7740],
      [53.2018, 5.7735],
      [53.2013, 5.7745],
    ],
    externalUrl: null,
    type: 'loop',
  },
  {
    id: 'jabikspaad',
    name_nl: 'Jabikspaad (pelgrimsroute)',
    name_en: 'Jabikspaad (pilgrimage route)',
    name_de: 'Jabikspaad (Pilgerweg)',
    distance: 'Etappe 8–25 km',
    duration_nl: 'Halve tot hele dag per etappe',
    duration_en: 'Half to full day per stage',
    duration_de: 'Halber bis ganzer Tag pro Etappe',
    difficulty_nl: 'Gemiddeld',
    difficulty_en: 'Moderate',
    difficulty_de: 'Mittel',
    desc_nl: 'De pelgrimsroute van St. Jabik (St. Jacobiparochie) via Friesland naar Santiago de Compostella loopt langs Túnmanswente — een officieel stempelpunt. Schitterende etappes door het Friese landschap. Alle etappe-beschrijvingen op jabikspaad.nl.',
    desc_en: 'The pilgrimage route from St. Jabik (St. Jacobiparochie) via Friesland to Santiago de Compostella passes Túnmanswente — an official stamp point. Lovely stages through the Frisian landscape. All stage descriptions on jabikspaad.nl.',
    desc_de: 'Der Pilgerweg von St. Jabik (St. Jacobiparochie) über Friesland nach Santiago de Compostella führt am Túnmanswente vorbei — einem offiziellen Stempelpunkt. Schöne Etappen durch die friesische Landschaft. Alle Etappenbeschreibungen auf jabikspaad.nl.',
    coords: [
      [53.3667, 5.6167],
      [53.3333, 5.6667],
      [53.2981, 5.7284],
      [53.2357, 5.7562],
      MARTENASTATE,
      LEEUWARDEN_OLDEHOVE,
    ],
    externalUrl: 'https://www.jabikspaad.nl/',
    type: 'longdistance',
  },
  {
    id: 'elfstedenpad',
    name_nl: 'Elfstedenpad (etappe Oentsjerk – Leeuwarden)',
    name_en: 'Elfstedenpad (stage Oentsjerk – Leeuwarden)',
    name_de: 'Elfstedenpad (Etappe Oentsjerk – Leeuwarden)',
    distance: '~15 km',
    duration_nl: '±4,5 uur',
    duration_en: '±4.5 hours',
    duration_de: '±4,5 Std.',
    difficulty_nl: 'Gemiddeld',
    difficulty_en: 'Moderate',
    difficulty_de: 'Mittel',
    desc_nl: 'Een etappe van het 300 km lange Elfstedenpad langs alle 11 Friese steden. Vanuit Oentsjerk richting Leeuwarden, passeert vlak langs Martenastate. Gemarkeerd met geel-rode tekens. Volledige routebeschrijving op wandelnet.nl.',
    desc_en: 'A stage of the 300 km Elfstedenpad through all 11 Frisian cities. From Oentsjerk towards Leeuwarden, passing close to Martenastate. Marked with yellow-red signs. Full route description on wandelnet.nl.',
    desc_de: 'Eine Etappe des 300 km langen Elfstedenpad durch alle 11 friesischen Städte. Von Oentsjerk nach Leeuwarden, vorbei an Martenastate. Markiert mit gelb-roten Zeichen. Vollständige Routenbeschreibung auf wandelnet.nl.',
    coords: [
      [53.2525, 5.8658],
      [53.2400, 5.8500],
      [53.2300, 5.8350],
      [53.2200, 5.8200],
      [53.2100, 5.8050],
      [53.2050, 5.8000],
      LEEUWARDEN_OLDEHOVE,
    ],
    externalUrl: 'https://www.wandelnet.nl/elfstedenpad',
    type: 'longdistance',
  },
  {
    id: 'noardlike-fryske-walden',
    name_nl: 'Noardlike Fryske Wâlden (vertrek Burgum)',
    name_en: 'Noardlike Fryske Wâlden (start Burgum)',
    name_de: 'Noardlike Fryske Wâlden (Start Burgum)',
    distance: '165 km totaal (etappes 9–25 km)',
    duration_nl: 'Etappes van halve tot hele dag',
    duration_en: 'Stages of half to full day',
    duration_de: 'Etappen von einem halben bis ganzen Tag',
    difficulty_nl: 'Gemiddeld',
    difficulty_en: 'Moderate',
    difficulty_de: 'Mittel',
    desc_nl: 'Langeafstandswandelpad van 165 km door de Noardlike Fryske Wâlden (Noordelijk Friese Wouden). Etappe 1 vertrekt uit Burgum (~25 km van Martenastate). Prachtig coulissenlandschap met houtwallen, poelen en boerderijen. Etappebeschrijvingen op wandelnet.nl.',
    desc_en: 'Long-distance walking path of 165 km through the Noardlike Fryske Wâlden (Northern Frisian Woods). Stage 1 departs from Burgum (~25 km from Martenastate). Beautiful landscape with hedgerows, ponds and farmsteads. Stage descriptions on wandelnet.nl.',
    desc_de: 'Fernwanderweg von 165 km durch die Noardlike Fryske Wâlden (Nördliche Friesische Wälder). Etappe 1 beginnt in Burgum (~25 km von Martenastate). Schöne Landschaft mit Hecken, Teichen und Bauernhöfen. Etappenbeschreibungen auf wandelnet.nl.',
    coords: [
      [53.1900, 6.0000],
      [53.2050, 6.0100],
      [53.2200, 6.0250],
      [53.2350, 6.0400],
      [53.2500, 6.0500],
    ],
    externalUrl: 'https://www.wandelnet.nl/noardlike-fryske-walden',
    type: 'longdistance',
  },
  {
    id: 'waddenwandelen',
    name_nl: 'Waddenwandelen (Holwerd – Waddenkust)',
    name_en: 'Wadden Coast Walk (Holwerd – Wadden coast)',
    name_de: 'Wattenwanderung (Holwerd – Wattenküste)',
    distance: '275 km totaal (17 dagtochten à 10–20 km)',
    duration_nl: 'Dagtochten van 3–6 uur',
    duration_en: 'Day walks of 3–6 hours',
    duration_de: 'Tagestouren von 3–6 Stunden',
    difficulty_nl: 'Gemiddeld',
    difficulty_en: 'Moderate',
    difficulty_de: 'Mittel',
    desc_nl: 'Wandelpad van 275 km langs de Friese Waddenkust, verdeeld in 17 dagtochten. Vertrekpunt Holwerd (~35 km van Martenastate) met uitzicht op Ameland. Langs dijken, kwelders en historische terpen. Alle dagtochten beschreven op wandelnet.nl.',
    desc_en: 'Walking route of 275 km along the Frisian Wadden Coast, divided into 17 day walks. Starting point Holwerd (~35 km from Martenastate) with views of Ameland. Along dykes, salt marshes and historic terps. All day walks described on wandelnet.nl.',
    desc_de: 'Wanderweg von 275 km entlang der friesischen Wattenküste, unterteilt in 17 Tagestouren. Startpunkt Holwerd (~35 km von Martenastate) mit Blick auf Ameland. Entlang Deichen, Salzwiesen und historischen Terpen.',
    coords: [
      [53.3750, 5.8900],
      [53.3900, 5.9200],
      [53.4050, 5.9500],
      [53.4200, 5.9800],
      [53.4400, 6.0200],
    ],
    externalUrl: 'https://www.wandelnet.nl/waddenwandelen',
    type: 'longdistance',
  },
];

const cyclingRoutes = [
  {
    id: 'elfstedenfietsroute',
    name_nl: 'Elfsteden Fietsroute',
    name_en: 'Eleven Cities Cycling Route',
    name_de: 'Elfsteden Radroute',
    distance: '~258 km',
    duration_nl: '3–5 dagen',
    duration_en: '3–5 days',
    duration_de: '3–5 Tage',
    difficulty_nl: 'Meerdaags',
    difficulty_en: 'Multi-day',
    difficulty_de: 'Mehrtägig',
    desc_nl: 'De klassieke fietsroute langs alle 11 Friese steden: Leeuwarden, Sneek, IJlst, Sloten, Stavoren, Hindeloopen, Workum, Bolsward, Harlingen, Franeker en Dokkum. Officieel startpunt in Leeuwarden (5 km van Martenastate). Volledig gemarkeerd met blauwe bordjes. Routebeschrijving op friesland.nl.',
    desc_en: 'The classic cycling route along all 11 Frisian cities: Leeuwarden, Sneek, IJlst, Sloten, Stavoren, Hindeloopen, Workum, Bolsward, Harlingen, Franeker and Dokkum. Official start in Leeuwarden (5 km from Martenastate). Fully marked with blue signs. Route description on friesland.nl.',
    desc_de: 'Die klassische Radroute durch alle 11 friesischen Städte: Leeuwarden, Sneek, IJlst, Sloten, Stavoren, Hindeloopen, Workum, Bolsward, Harlingen, Franeker und Dokkum. Offizieller Start in Leeuwarden (5 km von Martenastate). Vollständig mit blauen Schildern markiert.',
    coords: [
      LEEUWARDEN_OLDEHOVE,
      [53.1500, 5.8500],
      [53.0500, 5.7500],
      [52.9400, 5.4000],
      [53.1000, 5.4200],
      [53.1743, 5.4214],
      LEEUWARDEN_OLDEHOVE,
    ],
    externalUrl: 'https://www.friesland.nl/nl/routes/822249959/elfstedenfietsroute',
    type: 'longdistance',
  },
  {
    id: 'fryske-gea-route',
    name_nl: 'Fryske Gea Route (Alde Feanen)',
    name_en: 'Fryske Gea Route (Alde Feanen)',
    name_de: 'Fryske Gea Route (Alde Feanen)',
    distance: '~26 km lus',
    duration_nl: '±2 uur',
    duration_en: '±2 hours',
    duration_de: '±2 Std.',
    difficulty_nl: 'Gemakkelijk',
    difficulty_en: 'Easy',
    difficulty_de: 'Leicht',
    desc_nl: 'Korte lus van 26 km door Nationaal Park De Alde Feanen bij Earnewald, met 4 veerpont-oversteken. Prachtig laagveenlandschap met rietvelden en meren. Start in Earnewald (~30 km van Martenastate). Routebeschrijving op friesland.nl.',
    desc_en: 'Short 26 km loop through National Park De Alde Feanen near Earnewald, including 4 ferry crossings. Beautiful peat-fen landscape with reed beds and lakes. Start in Earnewald (~30 km from Martenastate). Route description on friesland.nl.',
    desc_de: 'Kurze 26 km Runde durch den Nationalpark De Alde Feanen bei Earnewald, mit 4 Fährüberfahrten. Schöne Niedermoorlandschaft mit Schilfflächen und Seen. Start in Earnewald (~30 km von Martenastate).',
    coords: [
      [53.0940, 5.9750],
      [53.0800, 5.9900],
      [53.0700, 6.0050],
      [53.0800, 6.0200],
      [53.0950, 6.0100],
      [53.1000, 5.9900],
      [53.0940, 5.9750],
    ],
    externalUrl: 'https://www.friesland.nl/nl/routes/2664920013/fryske-gea-route',
    type: 'loop',
  },
  {
    id: 'eetbaar-fryslan',
    name_nl: 'Eetbaar Fryslân – Leeuwarden–Burgum',
    name_en: 'Edible Friesland – Leeuwarden–Burgum',
    name_de: 'Essbares Friesland – Leeuwarden–Burgum',
    distance: '~39 km',
    duration_nl: '±2,5 uur',
    duration_en: '±2.5 hours',
    duration_de: '±2,5 Std.',
    difficulty_nl: 'Gemakkelijk',
    difficulty_en: 'Easy',
    difficulty_de: 'Leicht',
    desc_nl: 'Culinaire fietsroute van 39 km van Leeuwarden via het boerenland naar Burgum. Langs biologische boerderijen en lokale streekproducten. Perfecte dagrit vanuit Martenastate (5 km naar Leeuwarden). Routebeschrijving op friesland.nl.',
    desc_en: 'Culinary cycling route of 39 km from Leeuwarden through farmland to Burgum. Past organic farms and local produce. Perfect day ride from Martenastate (5 km to Leeuwarden). Route description on friesland.nl.',
    desc_de: 'Kulinarische Radroute von 39 km von Leeuwarden durch Ackerland nach Burgum. Vorbei an Biobauernhöfen und lokalen Produkten. Perfekte Tagestour von Martenastate (5 km nach Leeuwarden).',
    coords: [
      LEEUWARDEN_OLDEHOVE,
      [53.2100, 5.8300],
      [53.2000, 5.8800],
      [53.1900, 5.9300],
      BURGUM,
    ],
    externalUrl: 'https://www.friesland.nl/nl/routes/3600352704/eetbaar-fryslan-rondje-leeuwarden-burgum',
    type: 'oneway',
  },
  {
    id: 'middelzee-lf',
    name_nl: 'LF Middelzeeroute',
    name_en: 'LF Middelzee Route',
    name_de: 'LF Middelzee-Route',
    distance: '~145 km',
    duration_nl: '2–3 dagen',
    duration_en: '2–3 days',
    duration_de: '2–3 Tage',
    difficulty_nl: 'Meerdaags',
    difficulty_en: 'Multi-day',
    difficulty_de: 'Mehrtägig',
    desc_nl: 'Weekendroute van 145 km door het voormalige Middelzee-gebied en langs het Klooster Claercamppad. Langs kloosters, historische terpen en Friese coulissenlandschap. Vertrek vanuit Leeuwarden (5 km van Martenastate). Routebeschrijving op friesland.nl.',
    desc_en: 'Weekend route of 145 km through the former Middelzee area and along the Klooster Claercamppad. Past monasteries, historic terps and Frisian landscapes. Depart from Leeuwarden (5 km from Martenastate). Route description on friesland.nl.',
    desc_de: 'Wochenendroute von 145 km durch das ehemalige Middelzee-Gebiet und entlang des Klooster Claercamppads. Vorbei an Klöstern, historischen Terpen und friesischer Landschaft.',
    coords: [
      LEEUWARDEN_OLDEHOVE,
      [53.2500, 5.6500],
      [53.3000, 5.5500],
      [53.2000, 5.5000],
      [53.1000, 5.5500],
      [53.0500, 5.6000],
      [53.1000, 5.7000],
      LEEUWARDEN_OLDEHOVE,
    ],
    externalUrl: 'https://www.friesland.nl/nl/routes/3051993378/fietstocht-middelzeeroute-klooster-claercamppad',
    type: 'loop',
  },
  {
    id: 'waterbeleefroute',
    name_nl: 'Waterbeleefroute Fryslân',
    name_en: 'Water Experience Route Friesland',
    name_de: 'Wassererlebnisroute Friesland',
    distance: '~177 km',
    duration_nl: '3–4 dagen',
    duration_en: '3–4 days',
    duration_de: '3–4 Tage',
    difficulty_nl: 'Meerdaags',
    difficulty_en: 'Multi-day',
    difficulty_de: 'Mehrtägig',
    desc_nl: 'Fietstocht van 177 km langs de mooiste waterhotspots van Friesland: meren, kanalen, sluizen en boerenbruggetjes. Vertrekpunt Leeuwarden (5 km van Martenastate). Volledige routebeschrijving op friesland.nl.',
    desc_en: 'Cycling trip of 177 km past Friesland\'s most beautiful water hotspots: lakes, canals, locks and farm bridges. Starting point Leeuwarden (5 km from Martenastate). Full route description on friesland.nl.',
    desc_de: 'Radtour von 177 km an Frieslands schönsten Wasserhotspots entlang: Seen, Kanäle, Schleusen und Bauernbrücken. Ausgangspunkt Leeuwarden (5 km von Martenastate).',
    coords: [
      LEEUWARDEN_OLDEHOVE,
      [53.1500, 5.9000],
      [53.0500, 5.8500],
      [52.9500, 5.8000],
      [52.9000, 5.7000],
      [53.0000, 5.6000],
      [53.1000, 5.6500],
      LEEUWARDEN_OLDEHOVE,
    ],
    externalUrl: 'https://www.friesland.nl/nl/routes/2587522922/waterbeleefroute-waterhotspots-fryslan',
    type: 'longdistance',
  },
];
